[package]
name = "day-4"
version = "0.1.0"
authors = ["Alper Cugun-Gscheidel <alper.cugun-gscheidel@dcso.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
