[package]
name = "day-19"
version = "0.1.0"
authors = ["Alper Ã‡ugun <github@alper.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
regex = "1.4.2"