[package]
name = "day-23"
version = "0.1.0"
edition = "2021"

[dependencies]
# array2d = "0.2.1"
# grid = "0.6.0"
itertools = "0.10.3"
# nom = "7.1.1"
# rayon = "1.6.1"
# toodee = "0.3.0"
# pathfinding = "4.0.0"

[dev-dependencies]
test-case = "2.2.2"